### ISSUE TITLE
Symbol>>=> is overridden and should not

### ISSUE THREAD

**Issue by bergel** [juliendelplanque/Python3Generator#3]
Pharo 7 contains the method 
```Smalltalk
Symbol>>=> aVariable
	aVariable isBehavior
		ifTrue: [ ^ aVariable named: self].
	^ aVariable name: self;
		yourself
```
This method is overrides by Python3Generator, which is a serious problem.

**Comment by juliendelplanque** [comment]
Thank you for the report, I fixed this issue and created a new release.

Sorry for the delay.

Cheers,

Julien

PS: It was on the master branch but not on the old stable release (v1.0.0). If you seek stability, please consider using the stable release you prefer.
